apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-service
  template:
    metadata:
      labels:
        app: my-service
    spec:
      containers:
      - name: my-service
        image: your-docker-repo/my-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "development"
